### ISSUE TITLE
Issue loading Mod

### ISSUE THREAD

**Issue by RileyCasper** [Samlegamer/Macaw-s-Fences-Compat#1]
![image](https://user-images.githubusercontent.com/80489042/164582899-f0cca43c-d446-4571-b327-bb5facb90942.png)
I've tried every which way to get this to work. And I'm not sure if it's me or others are having it as well.

Attached is my Latest.log and Crash Log.
[latest.log](https://github.com/Samlegamer/Macaw-s-Fences-Compat/files/8536331/latest.log)
[crash-2022-04-21_21.01.59-fml.txt](https://github.com/Samlegamer/Macaw-s-Fences-Compat/files/8536335/crash-2022-04-21_21.01.59-fml.txt)

**Comment by Samlegamer** [comment]
this is due to the new version 1.0.4

**Comment by Samlegamer** [comment]
Fixed in 1.1
