### ISSUE TITLE
Minecraft fails to load since latest Macaw's bridges update

### ISSUE THREAD

**Issue by xenogray** [Samlegamer/Macaw-s-Fences-Compat#10]
Macaw's Bridges - BOP has failed to load correctly
java.lang.noClassDefFoundError:
com/mcwbridges/kikoz/objects/Iron_Stair

Since MCW bridges version 3.0.0

**Comment by Lord-Greyhawk** [comment]
Having the same problem. The regular mod runs and loads, but shows no available bridges. This mod is causing crashes on the load. Took me a fair amopunt of time to figure this out. I really hope this is fixed soon, as I have one Water World with boats conneted by floating bridges. I'm afraid to load it after my testing reset another mod, causing me to lose a bunch of stuff I built.

**Comment by Samlegamer** [comment]
updated
