### ISSUE TITLE
Multiple "Parsing error loading recipe" entries in server console

### ISSUE THREAD

**Issue by PJRamaglia** [Samlegamer/Macaw-s-Fences-Compat#13]
Encountering a bunch of the above mentioned entries in my local server's console when the server is first launching.  It doesn't seem like the client has the same errors though.  My client is able to connect to the local server as well without any apparent issue.
 
server-debug.log: https://gist.github.com/PJRamaglia/7cdf163ae8b8ef20c3176ae5a4784d29
server-latest.log: https://gist.github.com/PJRamaglia/567a9b0cb1ed479675f21c7e1b9c8685

client-debug.log: https://gist.github.com/PJRamaglia/1b0594d64cb640498d9f25ee74b767c7
client-latest.log: https://gist.github.com/PJRamaglia/369faa84c182131717b1400904a1229f

**Comment by makumaku1974** [comment]
Still hasn't been fixed till this day. I've used the mod from the day it updated and still hasn't got an update.

**Comment by Samlegamer** [comment]
The errors correspond to the Hedges of the original mod, they have slipped into the data, an update will soon be available to resolve this.

**Comment by Samlegamer** [comment]
patch is available
