### ISSUE TITLE
@OnlyIn(Dist.CLIENT) on 1.20.1 Forge causing server crash

### ISSUE THREAD

**Issue by TheUnifox** [Samlegamer/Macaw-s-Fences-Compat#15]
@OnlyIn(Dist.CLIENT) keeping methods from loading when installed on a dedicated server cause the mod to crash the server. Forge 1.20.1 is the file I looked at as thats the version I am attempting to use. Calling the function when on a server means it can't find the function, as it does not load when on a dedicated server. I have no idea about mod dev for Forge, but either removing the @OnlyIn(Dist.CLIENT) from the functions, if that doesnt cause a crash with what they are calling, or only trying to call them when loaded on a client, and not when on a server should fix it. I would fix it and PR, but I don't know Forge mod dev.

**Comment by TheUnifox** [comment]
Just a bit of quick research shows how to properly check server or client side. otherwise good mods, been using the base and byg addons on my fabric server a while now. the other byg addons on the new forge server havent caused issues yet, but it *could* just be this one crashing it first, before the others can

**Comment by Samlegamer** [comment]
Fixed in 1.20.1-1.1
