### ISSUE TITLE
Backport BOP compat to fabric 1.20.1

### ISSUE THREAD

**Issue by MimzyFang** [Samlegamer/Macaw-s-Fences-Compat#18]
Biomes O' Plenty was backported to fabric 1.20.1 https://modrinth.com/mod/biomes-o-plenty/version/sOaf66Bg

would love to see these compat mods on that version

**Comment by Samlegamer** [comment]
This is planned for the new addons to be released soon https://github.com/Samlegamer/Macaw-s-Addons/issues/1

**Comment by MimzyFang** [comment]
sweet looking forward to that
