### ISSUE TITLE
[1.19|Forge] Wired fences graphic bug

### ISSUE THREAD

**Issue by Illios42** [Samlegamer/Macaw-s-Fences-Compat#3]
We are using forge vers. 41.0.110, Macaw's fences vers. 1.0.5 and Macaw's fences for BoP vers. 1.1. The willow wired fences and the cherry wired fences work normally, yet every other wired fence seems to have a weird graphical error. Hope you could take a look at this!

![2022-07-27_19 04 23](https://user-images.githubusercontent.com/101580687/181311789-17c31a78-0a0e-4612-b32a-ec5ae3f599f1.png)

**Comment by Samlegamer** [comment]
fixed in mcwfencesbop-1.19.2-1.0
