### ISSUE TITLE
Axes are slower

### ISSUE THREAD

**Issue by ThatsAsh** [Samlegamer/Macaw-s-Fences-Compat#6]
It seams that when using axes with this mod they do not work properly. They are slower then normal, and some players have even said they just don't take any durability damage.

**Comment by ThisisCanada98** [comment]
Can confirm the issue as well, was able to narrow it down to Macaw's Fences - Oh The Biomes You'll Go. Have tried both version   
 [1.18.2-1.2] and version  [1.18.2-1.2]. Seems to remove the tool used for all wooden objects even things like chests and barrels.

**Comment by Samlegamer** [comment]
Fixed in mcwfencesbyg-1.18.2-1.3

https://www.curseforge.com/minecraft/mc-mods/macaws-fences-oh-the-biomes-youll-go/files/3926837
