### ISSUE TITLE
Mod failed to load correctly 

### ISSUE THREAD

**Issue by mimi-min** [Samlegamer/Macaw-s-Fences-Compat#7]
Crash Log: https://pastebin.com/GkXsg58z

Thank you for all of your wonderful mods btw!

**Comment by TheCrispyBarrett** [comment]
I'm having the same issue

**Comment by Thisguyneedshelp** [comment]
me as well, heres the normal log since i believe the crash log didnt have anything of importance this might be a little useful https://mclo.gs/1p7qIZ1

**Comment by Inkquill256** [comment]
I'm having the same issue.
Crash Log: [crash-2022-08-12_14.59.51-fml.txt](https://github.com/Samlegamer/Macaw-s-Fences-Compat/files/9329545/crash-2022-08-12_14.59.51-fml.txt)

Game Log: [latest.log](https://github.com/Samlegamer/Macaw-s-Fences-Compat/files/9329546/latest.log)

**Comment by Samlegamer** [comment]
fixed in 1.1
